{
 "title": "Apache Logs Dashboard",
 "tags": [
  "honeypot",
  "apache",
  "logs"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "Loki datasource", "query": "loki" },
   {
    "name": "type",
    "label": "Log type",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Errores HTTP Detallados",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"apache\",type=\"access\"} |~ \" [45][0-9][0-9] \" | regexp `(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+) - - \\[[^\\]]+\\] \\\"(?P<request>[A-Z]+ [^\\\"]+ HTTP/[0-9.]+)\\\" (?P<code>[45][0-9]{2})`"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate({job=\"apache\",type=\"access\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Status Codes (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (status)(rate({job=\"apache\",type=\"access\"}[1m]))"
    }
   ]
  },
  {
   "title": "Top 10 IPs by Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "topk(10, sum by (remote_ip) (count_over_time({job=\"apache\",type=\"access\"}[5m])))"
    }
   ]
  }
 ]
}